Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kconfig' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/kdbusaddons' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kdoctools' : '@same'

Options:
  test-before-installing: True
